### PR TITLE
first draft of json schema and pattern

### PR DESCRIPTION
**Pull request by tian2992**

### CODE REVIEW

**Comment by dl1com** [comment]
- Why do we need the field "filename"? We know the filename when we load the file, don't we?
- Can we mark fields as mandatory and optional in the validator?
- As you know from your development last year, you can't really tell the physical dimensions just from knowing the pixels/stitches of a pattern. You have to check in each an every case you change to another yarn (strength). So I propose to make the physical dimensions optional and add an optional "yarn strength" field

**Comment by tian2992** [comment]
@chris007de thanks for the advice!
- Filename is needed as we bundle the json file and the image in a zip file, or we can use a remote image. Maybe we can name it `url` ?
- Yes, we can set in the [schema fields as mandatory](https://github.com/fashiontec/knitpat/pull/1/files#diff-e24451c880853ab10ebb9b6b8343622bR44) all the others are optional, as well as mandatory and optional [as well in the subfields](https://github.com/fashiontec/knitpat/pull/1/files#diff-e24451c880853ab10ebb9b6b8343622bR34). 
- Had a bit of a doubt there, I will make physical size optional, add strength field.

Also I did not mention it explicitly, but we can use semi transparent files to set the trimming. e.g a circle with transparent values for empty places. However there might be use-cases where that is needed to be set differently, let me know what do you think please. Thanks!

**Comment by tian2992** [comment]
How can we define the yarn strength, does it have units?

**Comment by dl1com** [comment]
@tian2992 Yes, yarn strength has units - unfortunately not the same worldwide, and even several different in a single country ;)
Therefore I suggest to add another field for the unit of the yarn strength.

So I think we end up with physical size containing width, height, yarn strength, yarn strength unit.

Are there any other fields we need? Do you want to include the information about the used carriage and pattern width per line also in this json, or have another file for this?

**Comment by mariobehling** [comment]
@tian2992 Please create for every step an item in the issue tracker and allow us to follow the progress.

**Pull request merged**
